<?php
	if ($GLOBALS[called] == false) { 
		header("Location:/");
	}
	define(PageTitle, "Settings"); 
	include ("includes/header.php"); 
	
	// Only allow admins
	accessrestrist("admin");

	$a = general;
?>
	<!--- Content Start -->
	
	<div id="container">
	  <div id="content">
			<h1><img src="/images/icons/config.gif" class="icon" /> General Settings </h1>
			<hr />
			
			<?php messageArea(); ?>
		
			<div class="setting-block">
				<p><strong>Your Company Name</strong></p>
				<p class="subtext">This is the name shown at the top of your browser. It is also included on e-mail templates generated by the system.</p>
	
				<form action="/settings/save_settings/general" method="post" name="form" id="test" enctype="multipart/form-data">
				<input type='hidden' name='MAX_FILE_SIZE' VALUE='1000000'>
				<INPUT TYPE="HIDDEN" NAME="action" VALUE="1"> 
				<p><input type="text" name="companyname" size="45" value="<?=$GLOBALS[account][companyname]?>" /> </p>
				
			</div>
			
			<hr />
			
			<div class="setting-block">
				<p><strong>System Administrator</strong></p>
				<p class="subtext">This person is shown as the responsible party for managing the day-to-day running of your account. The list below shows all accounts which are part of this system. </p>
				<p><? selectUser("administrator", "", $GLOBALS[account][admin], "", "", ""); ?></p>
			</div>
			
			<hr />
			
			<div class="setting-block">
				<p><strong>Company Logo</strong></p>
				<p class="subtext">You can upload a logo for your company which will be displayed on your DeskLamp homepage and login screen.</p>
				<p>
				<?php
					if ($GLOBALS[account][logo] <> "") { 
						if ($GLOBALS[account][logo_border] == 1) { $border = "class=\"logoborder\""; }
						print "<img id=\"companylogo\" src=\"/images/logos/".$GLOBALS[account][logo]."\" $border>";
					}
				?>
				</p>
				<p><input type="file" name="logo" /> Maximum File Size: 60kb</p>
				<p><input type="checkbox" name="logo_border" onclick="<? if ($GLOBALS[account][logo] <> "") { print "changeLogoBorder(this)"; } ?>" value="1" <? if ($GLOBALS[account][logo_border] == 1) { print "checked=\"checked\""; } ?> /> Place a border around my logo</p>
				<p><input type="checkbox" name="logo_delete" value="1" onclick="if (confirmCheck('Are you sure you wish to delete this logo?\n\nYour logo will be deleted when you click \'Save Settings\'')) {  } else { this.checked = '' }" /> Delete this Logo</p>
	
				<p>&nbsp;</p>
				<p><input type="submit" name="submit" value="Save Settings" class="button2" /></p>
				</form>
			</div>			
	  </div>
		<div id="rightbar">
			<p><strong>System Settings</strong></p>
			<? include ("menu.php"); ?>			

		</div>
	</div>
	<!--- Content End -->

<?
	include ("includes/footer.php"); 
?>
